name: install

on:
  push:
    tags:
      - "v*"
    branches:
      - "**"
    paths:
      - ".github/workflows/install.yml"
      - "assets/**"
      - "**.py"
  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/install.yml"
      - "assets/**"
      - "**.py"
  workflow_dispatch:

jobs:
  meta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: set_tag
        run: |
          is_release=${{ startsWith(github.ref, 'refs/tags/v') }}
          tag=$(git describe --tags --match "v*" ${{ github.ref }} || true)
          if [[ $tag != v* ]]; then
            tag=$(curl -sX GET "https://api.github.com/repos/${{ github.repository }}/releases/latest" --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | awk '/tag_name/{print $4}' FS='["]')
            if [[ $tag != v* ]]; then
              tag="v0.0.0"
            fi
            tag=$(date "+$tag-%y%m%d-$(git rev-parse --short HEAD)")
          fi
          if ! $($is_release) ; then
            prefix=${tag%-*-*}
            suffix=${tag#$prefix-}
            tag="$prefix-ci.$suffix"
          fi

          echo tag=$tag | tee -a $GITHUB_OUTPUT
          echo is_release=$is_release | tee -a $GITHUB_OUTPUT
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
      is_release: ${{ steps.set_tag.outputs.is_release }}

  windows:
    needs: meta
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86_64]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download MaaFramework
        uses: robinraju/release-downloader@v1
        with:
          repository: MaaXYZ/MaaFramework
          fileName: "MAA-win-${{ matrix.arch }}*"
          latest: true
          out-file-path: "deps"
          extract: true

      - name: Download MFAWPF  
        uses: robinraju/release-downloader@v1  
        with:
          repository: SweetSmellFox/MFAWPF
          fileName: "MFAWPF*"
          latest: true
          out-file-path: "MFA"
          extract: true

      - name: Setup Embed Python
        shell: powershell
        run: |
          ./tools/ci/setup_embed_python.ps1

      - name: Install
        shell: bash
        run: |
          python ./tools/install.py ${{ needs.meta.outputs.tag }}
          cp MFA/MFAWPF.exe install

      - uses: actions/upload-artifact@v4
        with:
          name: M9A-win-${{ matrix.arch }}
          path: "install"

  ubuntu:
    needs: meta
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64, x86_64]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download MaaFramework
        uses: robinraju/release-downloader@v1
        with:
          repository: MaaXYZ/MaaFramework
          fileName: "MAA-linux-${{ matrix.arch }}*"
          latest: true
          out-file-path: "deps"
          extract: true

      - name: Download MFW
        uses: robinraju/release-downloader@v1
        with:
          repository: overflow65537/MFW-PyQt6
          fileName: "MFW-PyQt6-linux-${{ matrix.arch }}*"
          latest: true
          out-file-path: "install"
          extract: true


      - name: Install
        shell: bash
        run: |
          python ./tools/install.py ${{ needs.meta.outputs.tag }}

      - name: Install MFW
        shell: bash
        run: |
          rm install/MFW-PyQt6-linux-${{ matrix.arch }}*
          python ./tools/ci/deploy.py

      - uses: actions/upload-artifact@v4
        with:
          name: M9A-linux-${{ matrix.arch }}
          path: "install"


  macos:
    needs: meta
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [aarch64, x86_64]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download MaaFramework
        uses: robinraju/release-downloader@v1
        with:
          repository: MaaXYZ/MaaFramework
          fileName: "MAA-macos-${{ matrix.arch }}*"
          latest: true
          out-file-path: "deps"
          extract: true

      - name: Download MFW
        uses: robinraju/release-downloader@v1
        with:
          repository: overflow65537/MFW-PyQt6
          fileName: "MFW-PyQt6-macos-${{ matrix.arch }}*"
          latest: true
          out-file-path: "install"
          extract: true

      - name: Install
        shell: bash
        run: |
          python ./tools/install.py ${{ needs.meta.outputs.tag }}

      - name: Install MFW
        shell: bash
        run: |
          rm install/MFW-PyQt6-macos-${{ matrix.arch }}*
          python ./tools/ci/deploy.py
      - uses: actions/upload-artifact@v4
        with:
          name: M9A-macos-${{ matrix.arch }}
          path: "install"


  generate-changelog:
    if: ${{ needs.meta.outputs.is_release == 'true' }}
    needs: [meta]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 需要完整历史记录来生成变更日志

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install conventional-changelog
        run: npm install -g conventional-changelog-cli

      - name: Generate complete changelog
        run: |
          # 生成完整变更日志，包含所有版本
          conventional-changelog -p angular -i CHANGELOG.md -s -r 0
          
          # 使用 awk 提取当前版本和小版本的变更
          VERSION="${{ needs.meta.outputs.tag }}"
          MAJOR_MINOR=$(echo $VERSION | grep -o "v[0-9]*\.[0-9]*")
          
          echo "## What's Changed" > RELEASE_NOTES.md
          
          # 提取相关版本信息
          awk -v version="$MAJOR_MINOR" '
            /^## / { 
              if ($2 ~ "^"version) { 
                print; in_version = 1 
              } else if (in_version) { 
                exit 
              }
            }
            in_version { print }
          ' CHANGELOG.md >> RELEASE_NOTES.md
          
          # 添加完整变更日志链接
          echo -e "\nFull Changelog: $(git describe --tags --abbrev=0 --match "$MAJOR_MINOR.*" HEAD^)...$VERSION" >> RELEASE_NOTES.md
          
          # 输出生成的发布说明
          cat RELEASE_NOTES.md

      - name: Upload changelog artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-notes
          path: RELEASE_NOTES.md

  release:
    if: ${{ needs.meta.outputs.is_release == 'true' }}
    needs: [meta, windows, ubuntu, macos, generate-changelog]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: assets

      - name: Check assets directory
        run: |
          ls -la assets
          if [ -z "$(ls -A assets)" ]; then
            echo "assets directory is empty"
            exit 1
          fi

      - name: Prepare release notes
        run: |
          # 获取生成的发布说明
          mv assets/release-notes/RELEASE_NOTES.md ./RELEASE_NOTES.md
          # 删除成品中的release-notes目录
          rm -rf assets/release-notes

      - name: Compress and generate checksums
        run: |
          cd assets
          echo "Generating checksums for all zip files..."
          checksum_file="checksums.sha256"
          touch "$checksum_file"

          for f in *; do
            if [ -d "$f" ]; then
              echo "Processing directory: $f"
              zip_file="$f-${{ needs.meta.outputs.tag }}.zip"
              (cd "$f" && zip -r "../$zip_file" .)
              if [ $? -eq 0 ]; then
                echo "ZIP file created: ../$zip_file"
                echo "Processing directory: $f"
                sha256sum "$zip_file" >> "$checksum_file"
                echo "" >> "$checksum_file"
              else
                echo "Failed to create ZIP file: ../$zip_file"
                exit 1
              fi
            else
              echo "Skipping non-directory: $f"
            fi
          done

      - uses: softprops/action-gh-release@v2
        with:
          files: assets/*
          tag_name: ${{ needs.meta.outputs.tag }}
          body_path: RELEASE_NOTES.md

      - name: Trigger MirrorChyanUploading
        run: |
          gh workflow run --repo $GITHUB_REPOSITORY mirrorchyan
          gh workflow run --repo $GITHUB_REPOSITORY mirrorchyan_release_note
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
